"""Frappe's own form-control CSS for the standalone /todobox page.

The page cannot load website.bundle.css as a whole (Bootstrap's reboot, grid and
typography would restyle the entire app, and Frappe's :root variables --primary,
--red, --green, --shadow-* collide with the app's theme tokens). This takes the
CSS Frappe *built* (sites/assets/frappe/dist/css[-rtl]/website.bundle.*.css) and
keeps, unchanged, only the rules for form controls — .frappe-control, labels,
.form-control, Link/awesomplete, MultiSelectPills, the Quill Text Editor and the
air-datepicker — plus Frappe's CSS variables (light and dark), all scoped under
`.tm-frappe` (dark: `html[data-dark="1"] .tm-frappe`).

Output: public/css/frappe_controls.css and frappe_controls_rtl.css
Regenerate after a Frappe upgrade (bench build first):
	bench --site <site> execute todobox.setup.frappe_controls_css.generate
"""

import glob
import os
import re

import frappe

SCOPE = ".tm-frappe"
DARK_SCOPE = 'html[data-dark="1"] .tm-frappe'
KEYWORDS = (
	"form-control", "frappe-control", "control-label", "control-input", "control-value", "form-group",
	"awesomplete", "datepicker", "ql-", "table-multiselect", "data-pill", "tb-selected-value", "link-btn",
	"link-field", "btn-link-to-form", "btn-remove", "like-disabled-input", "help-box", "input-with-feedback",
	"has-error", "input-max-width", "input-xs", "input-sm", "clearfix", "text-muted", "text-extra-muted",
)
# element / utility selectors the controls rely on (Bootstrap reboot & Frappe icons)
EXACT = {"label", ".btn", ".btn:hover", ".btn:focus", ".btn.focus", ".icon", ".icon-xs", ".icon-sm", ".icon-md", ".es-icon", ".small", "small", ".hide", ".hidden"}
ROOTS = (":root", "[data-theme=light]", '[data-theme="light"]', "html")


def _wanted(selector: str) -> bool:
	s = selector.strip()
	return s in EXACT or any(k in s for k in KEYWORDS)


def _scope(selector: str) -> str | None:
	s = selector.strip()
	if s.startswith(("[data-theme=dark]", '[data-theme="dark"]')):
		rest = s.split("]", 1)[1].strip()
		return f"{DARK_SCOPE} {rest}" if rest else DARK_SCOPE
	if s in ROOTS:
		return SCOPE
	if s.startswith(("body", "html")):
		return None
	return f"{SCOPE} {s}"


def _serialize(tinycss2, nodes) -> str:
	return tinycss2.serialize(nodes).strip()


def _rules(tinycss2, nodes, out: list, variables: list, dark_variables: list):
	for node in nodes:
		if node.type == "qualified-rule":
			prelude = _serialize(tinycss2, node.prelude)
			selectors = [s.strip() for s in prelude.split(",")]
			body = _serialize(tinycss2, node.content)
			if all(s in ROOTS for s in selectors) and "--" in body:
				variables.append(body)
				continue
			if all(s in ("[data-theme=dark]", '[data-theme="dark"]') for s in selectors):
				dark_variables.append(body)
				continue
			keep = [_scope(s) for s in selectors if _wanted(s)]
			keep = [s for s in keep if s]
			if keep:
				out.append(f"{', '.join(keep)} {{ {body} }}")
		elif node.type == "at-rule" and node.lower_at_keyword in ("media", "supports") and node.content:
			inner: list = []
			_rules(tinycss2, tinycss2.parse_rule_list(node.content, skip_whitespace=True, skip_comments=True), inner, variables, dark_variables)
			if inner:
				out.append(f"@{node.at_keyword} {_serialize(tinycss2, node.prelude)} {{\n" + "\n".join(inner) + "\n}")


def build(css: str) -> str:
	import tinycss2

	out, variables, dark_variables = [], [], []
	_rules(tinycss2, tinycss2.parse_stylesheet(css, skip_whitespace=True, skip_comments=True), out, variables, dark_variables)
	head = [f"{SCOPE} {{ {v} }}" for v in variables] + [f"{DARK_SCOPE} {{ {v} }}" for v in dark_variables]
	return "\n".join(head + out) + "\n"


def generate():
	dist = os.path.abspath(os.path.join(frappe.utils.get_bench_path(), "sites", "assets", "frappe", "dist"))
	target = frappe.get_app_path("todobox", "public", "css")
	for folder, name in (("css", "frappe_controls.css"), ("css-rtl", "frappe_controls_rtl.css")):
		source = sorted(glob.glob(os.path.join(dist, folder, "website.bundle.*.css")), key=os.path.getmtime)[-1]
		with open(source) as f:
			css = build(f.read())
		header = (
			f"/* Generated by todobox/setup/frappe_controls_css.py from Frappe's {folder}/"
			f"{os.path.basename(source)}: Frappe's form-control CSS, unchanged, scoped to {SCOPE}. Do not edit. */\n"
		)
		with open(os.path.join(target, name), "w") as f:
			f.write(header + re.sub(r"\n{2,}", "\n", css))
		print(name, len(css))
